#!/bin/bash

source /scripts/functions/get_block
source /scripts/functions/get_public_ip

TIMESTAMP=$(date +%s)
LOG_FILE=${NODE_PATH}/logs/submit_topology.${TIMESTAMP}.json.log

mkdir -p ${NODE_PATH}/logs/

NWMAGIC=$(jq -r .networkMagic < ${NODE_PATH}/shelley-genesis.json)
BLOCK=$(get_block)
PUBLIC_IP=$(get_public_ip)

echo "Submitting node IP to api.clio.one" | tee -a $LOG_FILE

echo "Network Magic: ${NWMAGIC}" | tee -a $LOG_FILE
echo "Block: ${BLOCK}" | tee -a $LOG_FILE
echo "IP: ${PUBLIC_IP}" | tee -a $LOG_FILE
echo "Port: ${NODE_PORT}" | tee -a $LOG_FILE

curl -v "https://api.clio.one/htopology/v1/?port=${NODE_PORT}&blockNo=${BLOCK}&valency=1&magic=${NWMAGIC}" | tee -a $LOG_FILE

cat $LOG_FILE
